import { describe, expect, test } from 'bun:test';
import Database from 'bun:sqlite';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { createMemoryKernel } from '../src/factory.js';
import { explainRecallWithKernel } from '../src/recall/RecallExplanation.js';
import { EventStore } from '../src/store/EventStore.js';
import { TemporalAdjacencyStore } from '../src/store/TemporalAdjacencyStore.js';
import { TopologyStore } from '../src/store/TopologyStore.js';
import { nextCivilDate } from '../src/utils/LocalDateContext.js';
import type { TimeBucketRecord } from '../src/types/index.js';

const bucket = (id: string, start: number, end: number, type: TimeBucketRecord['bucketType'] = 'day'): TimeBucketRecord => ({
  bucketId: id,
  bucketType: type,
  bucketStart: start,
  bucketEnd: end,
  label: id,
});

describe('project-local temporal topology regressions', () => {
  test('time windows use half-open overlap semantics', () => {
    const db = new Database(':memory:');
    const topology = new TopologyStore(db);
    const adjacency = new TemporalAdjacencyStore(db);
    for (const item of [bucket('previous', 0, 10), bucket('target', 10, 20), bucket('next', 20, 30)]) topology.upsertTimeBucket(item);

    const surface = adjacency.collectContinuousSurface({ startTime: 10, endTime: 20, preferredBucketType: 'day' });
    expect(surface.bucketIds).toEqual(['target']);
    adjacency.close();
    topology.close();
  });

  test('out-of-order buckets replace obsolete skip adjacency', () => {
    const db = new Database(':memory:');
    const topology = new TopologyStore(db);
    const adjacency = new TemporalAdjacencyStore(db);
    const january = bucket('month:jan', 0, 10, 'month');
    const february = bucket('month:feb', 10, 20, 'month');
    const march = bucket('month:mar', 20, 30, 'month');
    topology.upsertTimeBucket(january); adjacency.syncBuckets([january], 1);
    topology.upsertTimeBucket(march); adjacency.syncBuckets([march], 2);
    topology.upsertTimeBucket(february); adjacency.syncBuckets([february], 3);

    const rows = db.prepare(`SELECT source_bucket_id,adjacent_bucket_id FROM temporal_adjacency ORDER BY source_bucket_id,adjacent_bucket_id`).all();
    expect(rows).toEqual([
      { source_bucket_id: 'month:feb', adjacent_bucket_id: 'month:jan' },
      { source_bucket_id: 'month:feb', adjacent_bucket_id: 'month:mar' },
      { source_bucket_id: 'month:jan', adjacent_bucket_id: 'month:feb' },
      { source_bucket_id: 'month:mar', adjacent_bucket_id: 'month:feb' },
    ]);
    adjacency.close();
    topology.close();
  });

  test('continuous bands never synthesize fixed-duration calendar buckets', () => {
    const db = new Database(':memory:');
    const topology = new TopologyStore(db);
    const adjacency = new TemporalAdjacencyStore(db);
    topology.upsertTimeBucket(bucket('month:real-a', 0, 28, 'month'));
    topology.upsertTimeBucket(bucket('month:real-b', 59, 90, 'month'));
    const surface = adjacency.collectContinuousSurface({ startTime: 0, endTime: 90, preferredBucketType: 'month' });
    expect(surface.bucketIds).toEqual(['month:real-a', 'month:real-b']);
    adjacency.close();
    topology.close();
  });

  test('next civil date skips dates that do not exist in the project timezone', () => {
    expect(nextCivilDate(2011, 12, 29, 1, 'Pacific/Apia')).toEqual([2011, 12, 31]);
  });

  test('event provenance is generated by the store and cannot be forged', () => {
    const store = new EventStore(':memory:', undefined, 'Asia/Tokyo');
    const projectEvent = store.append({ streamId: 'p', streamType: 'thread', eventType: 'MESSAGE', occurredAt: Date.UTC(2026, 6, 16, 15, 30), payload: {} });
    expect(projectEvent.localDate).toBe('2026-07-17');
    expect(projectEvent.localDateSource).toBe('generated_project_timezone');
    const explicitZone = store.append({ streamId: 'z', streamType: 'thread', eventType: 'MESSAGE', occurredAt: Date.UTC(2026, 6, 17, 6, 30), timeZone: 'America/Los_Angeles', payload: {} });
    expect(explicitZone.localDateSource).toBe('generated_explicit_timezone');
    expect(() => store.append({ streamId: 'bad', streamType: 'thread', eventType: 'MESSAGE', occurredAt: 0, localDate: '2035-01-01', localDateSource: 'generated_utc', payload: {} } as never)).toThrow('invalid_local_date_source');
    store.close();
  });

  test('non-agent recall explanation forwards the same explicit clock to fallback recall', () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const calls: Array<Record<string, unknown>> = [];
    const originalRecall = kernel.recall.bind(kernel);
    (kernel as unknown as { recall: typeof kernel.recall }).recall = ((query: string, options: Record<string, unknown>) => {
      calls.push(options);
      return originalRecall(query, options);
    }) as typeof kernel.recall;
    explainRecallWithKernel(kernel, { query: 'today', projectId: 'p', now: 123, localDateNow: '2026-07-17', timeZone: 'Asia/Tokyo' });
    expect(calls[0]).toMatchObject({ now: 123, localDateNow: '2026-07-17', timeZone: 'Asia/Tokyo' });
    kernel.close();
  });

  test('dirty legacy time topology is rebuilt lazily per project', async () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'America/Los_Angeles' });
    await kernel.ingest({ projectId: 'p', content: 'civil topology rebuild evidence' });
    kernel.topologyStore.markTimeProjection('p', 'dirty', 'America/Los_Angeles', 1);
    expect(kernel.topologyStore.timeProjectionNeedsRebuild('p', 'America/Los_Angeles')).toBe(true);
    kernel.navigateMemory('civil topology', { projectId: 'p' });
    expect(kernel.topologyStore.timeProjectionNeedsRebuild('p', 'America/Los_Angeles')).toBe(false);
    kernel.close();
  });

  test('ingest preserves a dirty projection until timezone rebuild removes stale memberships', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'cogmem-timezone-rebuild-'));
    const dbPath = join(dir, 'memory.db');
    let kernel = createMemoryKernel({ dbPath, projectTimeZone: 'UTC' });
    await kernel.ingest({ projectId: 'p', content: 'old timezone evidence', occurredAt: Date.UTC(2026, 6, 16, 15, 30) });
    kernel.topologyStore.markTimeProjection('p', 'dirty', 'UTC', 1);
    kernel.close();

    kernel = createMemoryKernel({ dbPath, projectTimeZone: 'Asia/Tokyo' });
    await kernel.ingest({ projectId: 'p', content: 'new timezone evidence', occurredAt: Date.UTC(2026, 6, 17, 0, 30) });
    expect(kernel.topologyStore.timeProjectionNeedsRebuild('p', 'Asia/Tokyo')).toBe(true);
    kernel.navigateMemory('timezone evidence', { projectId: 'p' });

    const db = kernel.factStore.getDatabase();
    const memberships = db.prepare(`
      SELECT tm.dimension_key, tb.label
      FROM topology_membership tm
      JOIN time_buckets tb ON tb.bucket_id=tm.dimension_key
      WHERE tm.project_id='p' AND tm.dimension_type='time_bucket'
      ORDER BY tm.dimension_key
    `).all() as Array<{ dimension_key: string; label: string }>;
    expect(kernel.topologyStore.timeProjectionNeedsRebuild('p', 'Asia/Tokyo')).toBe(false);
    expect(new Set(memberships.map((row) => row.dimension_key)).size).toBe(3);
    expect(memberships.some((row) => row.label === '2026-07-17')).toBe(true);
    expect(memberships.some((row) => row.label === '2026-07-16')).toBe(false);
    kernel.close();
  });

  test('lazy timezone rebuilds never expose another project through temporal traversal', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'cogmem-project-time-scope-'));
    const dbPath = join(dir, 'memory.db');
    let kernel = createMemoryKernel({ dbPath, projectTimeZone: 'UTC' });
    const projectA = await kernel.ingest({
      projectId: 'project-a',
      content: 'project a temporal scope evidence',
      occurredAt: Date.UTC(2026, 6, 16, 15, 30),
    });
    const projectB = await kernel.ingest({
      projectId: 'project-b',
      content: 'project b must remain isolated',
      occurredAt: Date.UTC(2026, 6, 17, 15, 30),
    });
    kernel.topologyStore.markTimeProjection('project-a', 'dirty', 'UTC', 1);
    kernel.topologyStore.markTimeProjection('project-b', 'dirty', 'UTC', 1);
    kernel.close();

    kernel = createMemoryKernel({ dbPath, projectTimeZone: 'Asia/Tokyo' });
    const result = kernel.navigateMemory('project a temporal scope evidence', { projectId: 'project-a' });
    const tracedIds = new Set([
      ...(result.navigation?.branchSearch.temporalTraversal.neuronIds || []),
      ...(result.navigation?.branchSearch.temporalTraversal.segments.flatMap((segment) => segment.neuronIds) || []),
      ...(result.navigation?.pulse.pulse2Ids || []),
    ]);
    expect(tracedIds.has(projectA.id)).toBe(true);
    expect(tracedIds.has(projectB.id)).toBe(false);
    for (const neuronId of tracedIds) {
      expect(kernel.memoryGraph.getNeuron(neuronId)?.metadata.projectId).toBe('project-a');
    }
    kernel.close();
  });
});
