import { describe, expect, test } from 'bun:test';
import Database from 'bun:sqlite';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { createMemoryKernel } from '../src/factory.js';
import { NeuronFactory } from '../src/core/Neuron.js';
import { explainRecallWithKernel } from '../src/recall/RecallExplanation.js';
import { TopologyCompiler } from '../src/engine/TopologyCompiler.js';
import { EventStore } from '../src/store/EventStore.js';
import { TemporalAdjacencyStore } from '../src/store/TemporalAdjacencyStore.js';
import { TopologyStore } from '../src/store/TopologyStore.js';
import { TemporalBranchSearch } from '../src/retrieval/TemporalBranchSearch.js';
import { CognitiveGraphStore } from '../src/store/CognitiveGraphStore.js';
import { localDateRange, nextCivilDate } from '../src/utils/LocalDateContext.js';
import { timeBucketId } from '../src/topology/TimeBucketIdentity.js';
import { SchemaMigrationRunner, migration_0051 } from '../src/migrations/index.js';
import type { TimeBucketRecord } from '../src/types/index.js';

const bucket = (id: string, start: number, end: number, type: TimeBucketRecord['bucketType'] = 'day'): TimeBucketRecord => ({
  bucketId: id,
  bucketType: type,
  bucketStart: start,
  bucketEnd: end,
  label: id,
});

describe('project-local temporal topology regressions', () => {
  test('time windows use half-open overlap semantics', () => {
    const db = new Database(':memory:');
    const topology = new TopologyStore(db);
    const adjacency = new TemporalAdjacencyStore(db);
    for (const item of [bucket('previous', 0, 10), bucket('target', 10, 20), bucket('next', 20, 30)]) topology.upsertTimeBucket(item);

    const surface = adjacency.collectContinuousSurface({ startTime: 10, endTime: 20, preferredBucketType: 'day' });
    expect(surface.bucketIds).toEqual(['target']);
    adjacency.close();
    topology.close();
  });

  test('Unix epoch zero remains a real temporal boundary', () => {
    const db = new Database(':memory:');
    const topology = new TopologyStore(db);
    const adjacency = new TemporalAdjacencyStore(db);
    topology.upsertTimeBucket(bucket('epoch', 0, 10));
    const result = new TemporalBranchSearch(topology, adjacency).search({ startTime: 0, endTime: 10, terms: [] });
    expect(result.temporalTraversal.bucketIds).toEqual(['epoch']);
    expect(result.reasons).toContain('continuous temporal surface navigation across adjacent windows');
    adjacency.close();
    topology.close();
  });

  test('out-of-order buckets replace obsolete skip adjacency', () => {
    const db = new Database(':memory:');
    const topology = new TopologyStore(db);
    const adjacency = new TemporalAdjacencyStore(db);
    const january = bucket('month:jan', 0, 10, 'month');
    const february = bucket('month:feb', 10, 20, 'month');
    const march = bucket('month:mar', 20, 30, 'month');
    topology.upsertTimeBucket(january); adjacency.syncBuckets([january], 1);
    topology.upsertTimeBucket(march); adjacency.syncBuckets([march], 2);
    topology.upsertTimeBucket(february); adjacency.syncBuckets([february], 3);

    const rows = db.prepare(`SELECT source_bucket_id,adjacent_bucket_id FROM temporal_adjacency ORDER BY source_bucket_id,adjacent_bucket_id`).all();
    expect(rows).toEqual([
      { source_bucket_id: 'month:feb', adjacent_bucket_id: 'month:jan' },
      { source_bucket_id: 'month:feb', adjacent_bucket_id: 'month:mar' },
      { source_bucket_id: 'month:jan', adjacent_bucket_id: 'month:feb' },
      { source_bucket_id: 'month:mar', adjacent_bucket_id: 'month:feb' },
    ]);
    adjacency.close();
    topology.close();
  });

  test('continuous bands never synthesize fixed-duration calendar buckets', () => {
    const db = new Database(':memory:');
    const topology = new TopologyStore(db);
    const adjacency = new TemporalAdjacencyStore(db);
    topology.upsertTimeBucket(bucket('month:real-a', 0, 28, 'month'));
    topology.upsertTimeBucket(bucket('month:real-b', 59, 90, 'month'));
    const surface = adjacency.collectContinuousSurface({ startTime: 0, endTime: 90, preferredBucketType: 'month' });
    expect(surface.bucketIds).toEqual(['month:real-a', 'month:real-b']);
    adjacency.close();
    topology.close();
  });

  test('next civil date skips dates that do not exist in the project timezone', () => {
    expect(nextCivilDate(2011, 12, 29, 1, 'Pacific/Apia')).toEqual([2011, 12, 31]);
  });

  test('event provenance is generated by the store and cannot be forged', () => {
    const store = new EventStore(':memory:', undefined, 'Asia/Tokyo');
    const projectEvent = store.append({ streamId: 'p', streamType: 'thread', eventType: 'MESSAGE', occurredAt: Date.UTC(2026, 6, 16, 15, 30), payload: {} });
    expect(projectEvent.localDate).toBe('2026-07-17');
    expect(projectEvent.localDateSource).toBe('generated_project_timezone');
    const explicitZone = store.append({ streamId: 'z', streamType: 'thread', eventType: 'MESSAGE', occurredAt: Date.UTC(2026, 6, 17, 6, 30), timeZone: 'America/Los_Angeles', payload: {} });
    expect(explicitZone.localDateSource).toBe('generated_explicit_timezone');
    expect(() => store.append({ streamId: 'bad', streamType: 'thread', eventType: 'MESSAGE', occurredAt: 0, localDate: '2035-01-01', localDateSource: 'generated_utc', payload: {} } as never)).toThrow('invalid_local_date_source');
    expect(() => store.append({ streamId: 'bad-explicit', streamType: 'thread', eventType: 'MESSAGE', occurredAt: 0, localDate: '2035-01-01', timeZone: 'UTC', payload: {} })).toThrow('explicit_local_date_timestamp_mismatch');
    expect(() => store.append({ streamId: 'bad-project-zone', streamType: 'thread', eventType: 'MESSAGE', occurredAt: 0, projectTimeZone: 'America/Los_Angeles', payload: {} })).toThrow('project_timezone_override_forbidden');
    store.close();
  });

  test('non-agent recall explanation forwards the same explicit clock to fallback recall', () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const calls: Array<Record<string, unknown>> = [];
    const originalRecall = kernel.recall.bind(kernel);
    (kernel as unknown as { recall: typeof kernel.recall }).recall = ((query: string, options: Record<string, unknown>) => {
      calls.push(options);
      return originalRecall(query, options);
    }) as typeof kernel.recall;
    explainRecallWithKernel(kernel, { query: 'today', projectId: 'p', now: 123, localDateNow: '2026-07-17', timeZone: 'Asia/Tokyo' });
    expect(calls[0]).toMatchObject({ now: 123, localDateNow: '2026-07-17', timeZone: 'Asia/Tokyo' });
    kernel.close();
  });

  test('dirty legacy time topology stays read-only until explicit project rebuild', async () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'America/Los_Angeles' });
    await kernel.ingest({ projectId: 'p', content: 'civil topology rebuild evidence' });
    kernel.topologyStore.markTimeProjection('p', 'dirty', 'America/Los_Angeles', 1);
    expect(kernel.topologyStore.timeProjectionNeedsRebuild('p', 'America/Los_Angeles')).toBe(true);
    kernel.navigateMemory('civil topology', { projectId: 'p' });
    expect(kernel.topologyStore.timeProjectionNeedsRebuild('p', 'America/Los_Angeles')).toBe(true);
    kernel.rebuildProjectTimeTopology('p');
    expect(kernel.topologyStore.timeProjectionNeedsRebuild('p', 'America/Los_Angeles')).toBe(false);
    kernel.close();
  });

  test('explicit topology rebuild resumes from a persisted staging cursor', async () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    await kernel.ingest({ projectId: 'p', content: 'first staged topology neuron', occurredAt: 1000 });
    await kernel.ingest({ projectId: 'p', content: 'second staged topology neuron', occurredAt: 2000 });
    const neurons = kernel.memoryGraph.listTimeProjectionNeurons('p', { limit: 10 });
    expect(neurons).toHaveLength(2);

    const generation = 'test-resume-generation';
    const first = neurons[0]!;
    const planned = new TopologyCompiler(kernel.topologyStore).planTimeBuckets([first], 'UTC').get(first.id)!;
    const db = kernel.factStore.getDatabase();
    db.transaction(() => {
      db.prepare(`INSERT INTO topology_time_rebuild_jobs(project_id,generation,time_zone,status,cursor_created_at,cursor_neuron_id,neuron_count,updated_at,error,source_revision) VALUES(?,?,?,'building',?,?,1,?,NULL,?)`).run('p', generation, 'UTC', first.createdAt, first.id, 1000, kernel.topologyStore.getTimeProjectionSourceRevision('p'));
      const insertBucket = db.prepare(`INSERT INTO topology_time_rebuild_buckets(generation,bucket_id,project_id,time_zone,bucket_type,bucket_start,bucket_end,label) VALUES(?,?,?,?,?,?,?,?)`);
      const insertEntry = db.prepare(`INSERT INTO topology_time_rebuild_entries(generation,bucket_id,neuron_id,project_id,created_at) VALUES(?,?,?,?,?)`);
      for (const entry of planned) {
        insertBucket.run(generation, entry.bucketId, 'p', 'UTC', entry.bucketType, entry.bucketStart, entry.bucketEnd, entry.label);
        insertEntry.run(generation, entry.bucketId, first.id, 'p', first.createdAt);
      }
      kernel.topologyStore.markTimeProjection('p', 'building', 'UTC', 1000);
    })();

    const rebuilt = kernel.rebuildProjectTimeTopology('p');
    expect(rebuilt.neurons).toBe(2);
    expect(rebuilt.buckets).toBe(3);
    expect(db.prepare(`SELECT COUNT(*) AS count FROM topology_time_rebuild_jobs`).get()).toEqual({ count: 0 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM topology_time_rebuild_entries`).get()).toEqual({ count: 0 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM time_bucket_entries WHERE project_id='p'`).get()).toEqual({ count: 6 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM cognitive_nodes WHERE project_id='p' AND node_type='time_bucket'`).get()).toEqual({ count: 3 });
    kernel.close();
  });

  test('ingest preserves a dirty projection until timezone rebuild removes stale memberships', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'cogmem-timezone-rebuild-'));
    const dbPath = join(dir, 'memory.db');
    let kernel = createMemoryKernel({ dbPath, projectTimeZone: 'UTC' });
    await kernel.ingest({ projectId: 'p', content: 'old timezone evidence', createdAt: Date.UTC(2026, 6, 16, 15, 30) });
    kernel.topologyStore.markTimeProjection('p', 'dirty', 'UTC', 1);
    kernel.close();

    kernel = createMemoryKernel({ dbPath, projectTimeZone: 'Asia/Tokyo' });
    await kernel.ingest({ projectId: 'p', content: 'new timezone evidence', createdAt: Date.UTC(2026, 6, 17, 0, 30) });
    expect(kernel.topologyStore.timeProjectionNeedsRebuild('p', 'Asia/Tokyo')).toBe(true);
    kernel.navigateMemory('timezone evidence', { projectId: 'p' });
    expect(kernel.topologyStore.timeProjectionNeedsRebuild('p', 'Asia/Tokyo')).toBe(true);
    kernel.rebuildProjectTimeTopology('p');

    const db = kernel.factStore.getDatabase();
    const memberships = db.prepare(`
      SELECT tm.dimension_key, tb.label
      FROM topology_membership tm
      JOIN time_buckets tb ON tb.bucket_id=tm.dimension_key
      WHERE tm.project_id='p' AND tm.dimension_type='time_bucket'
      ORDER BY tm.dimension_key
    `).all() as Array<{ dimension_key: string; label: string }>;
    expect(kernel.topologyStore.timeProjectionNeedsRebuild('p', 'Asia/Tokyo')).toBe(false);
    expect(new Set(memberships.map((row) => row.dimension_key)).size).toBe(3);
    expect(memberships.some((row) => row.label === '2026-07-17')).toBe(true);
    expect(memberships.some((row) => row.label === '2026-07-16')).toBe(false);
    kernel.close();
  });

  test('explicit timezone rebuilds never expose another project through temporal traversal', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'cogmem-project-time-scope-'));
    const dbPath = join(dir, 'memory.db');
    let kernel = createMemoryKernel({ dbPath, projectTimeZone: 'UTC' });
    const projectA = await kernel.ingest({
      projectId: 'project-a',
      content: 'project a temporal scope evidence',
      occurredAt: Date.UTC(2026, 6, 16, 15, 30),
    });
    const projectB = await kernel.ingest({
      projectId: 'project-b',
      content: 'project b must remain isolated',
      occurredAt: Date.UTC(2026, 6, 17, 15, 30),
    });
    kernel.topologyStore.markTimeProjection('project-a', 'dirty', 'UTC', 1);
    kernel.topologyStore.markTimeProjection('project-b', 'dirty', 'UTC', 1);
    kernel.close();

    kernel = createMemoryKernel({ dbPath, projectTimeZone: 'Asia/Tokyo' });
    kernel.rebuildProjectTimeTopology('project-a');
    const result = kernel.navigateMemory('project a temporal scope evidence', { projectId: 'project-a' });
    const tracedIds = new Set([
      ...(result.navigation?.branchSearch.temporalTraversal.neuronIds || []),
      ...(result.navigation?.branchSearch.temporalTraversal.segments.flatMap((segment) => segment.neuronIds) || []),
      ...(result.navigation?.pulse.pulse2Ids || []),
    ]);
    expect(tracedIds.has(projectA.id)).toBe(true);
    expect(tracedIds.has(projectB.id)).toBe(false);
    for (const neuronId of tracedIds) {
      expect(kernel.memoryGraph.getNeuron(neuronId)?.metadata.projectId).toBe('project-a');
    }
    kernel.close();
  });

  test('cognitive and civil time identities stay isolated across alternating projects', async () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const occurredAt = Date.UTC(2026, 6, 17, 12);
    await kernel.ingest({ projectId: 'project-a', content: 'project a first write', occurredAt });
    await kernel.ingest({ projectId: 'project-b', content: 'project b same day write', occurredAt });
    await kernel.ingest({ projectId: 'project-a', content: 'project a second write', occurredAt: occurredAt + 1 });

    const db = kernel.factStore.getDatabase();
    const cognitiveRows = db.prepare(`SELECT node_id,project_id,node_key FROM cognitive_nodes WHERE node_type='time_bucket' ORDER BY project_id,node_key`).all() as Array<{ node_id: string; project_id: string; node_key: string }>;
    const bucketRows = db.prepare(`SELECT bucket_id,project_id,time_zone,bucket_type,bucket_start,bucket_end FROM time_buckets ORDER BY project_id,bucket_type`).all() as Array<{ bucket_id: string; project_id: string; time_zone: string; bucket_type: string; bucket_start: number; bucket_end: number }>;
    expect(cognitiveRows.filter((row) => row.project_id === 'project-a')).toHaveLength(3);
    expect(cognitiveRows.filter((row) => row.project_id === 'project-b')).toHaveLength(3);
    expect(new Set(cognitiveRows.map((row) => row.node_id)).size).toBe(6);
    expect(new Set(bucketRows.map((row) => row.bucket_id)).size).toBe(6);
    expect(bucketRows.every((row) => row.time_zone === 'UTC')).toBe(true);
    kernel.close();
  });

  test('projectless memories use a recoverable global time projection', async () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const first = await kernel.ingest({ content: 'global scope temporal evidence one', createdAt: Date.UTC(2026, 6, 17, 12) });
    const second = await kernel.ingest({ content: 'global scope temporal evidence two', createdAt: Date.UTC(2026, 6, 18, 12) });
    const db = kernel.factStore.getDatabase();
    kernel.topologyStore.markTimeProjection('', 'dirty', 'UTC', 1);
    db.prepare(`DELETE FROM temporal_adjacency WHERE project_id=''`).run();
    db.prepare(`DELETE FROM cognitive_edges WHERE project_id='' AND edge_type='occurred_in_time_bucket'`).run();
    db.prepare(`DELETE FROM cognitive_nodes WHERE project_id='' AND node_type='time_bucket'`).run();

    const rebuilt = kernel.rebuildProjectTimeTopology();
    expect(rebuilt.projectId).toBe('');
    expect(rebuilt.neurons).toBe(2);
    expect(db.prepare(`SELECT COUNT(*) AS count FROM time_bucket_entries WHERE project_id='' AND neuron_id IN (?,?)`).get(first.id, second.id)).toEqual({ count: 6 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM cognitive_nodes WHERE project_id='' AND node_type='time_bucket'`).get()).toEqual({ count: 4 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM temporal_adjacency WHERE project_id=''`).get()).toEqual({ count: 2 });
    expect(kernel.topologyStore.hasUsableTimeProjection('', 'UTC')).toBe(true);
    kernel.close();
  });

  test('first projectless ingest is immediately date-recallable with non-null global temporal scope', async () => {
    const at = Date.UTC(2026, 6, 17, 12);
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const neuron = await kernel.ingest({ content: 'first global date evidence', createdAt: at });
    const db = kernel.factStore.getDatabase();
    expect(db.prepare(`SELECT COUNT(*) AS count FROM time_bucket_entries WHERE neuron_id=? AND project_id=''`).get(neuron.id)).toEqual({ count: 3 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM time_bucket_entries WHERE neuron_id=? AND project_id IS NULL`).get(neuron.id)).toEqual({ count: 0 });
    expect(kernel.navigateMemory('2026-07-17', { projectId: '', startTime: at, endTime: at + 1 }).rawEvidence.map((item) => item.id)).toContain(neuron.id);
    kernel.close();
  });

  test('global scope stays isolated across FTS, topology, cognitive graph, ledger, and final recall', async () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const globalNeuron = await kernel.ingest({ content: 'scope collision omega global evidence', createdAt: 1000 });
    const projectNeuron = await kernel.ingest({ projectId: 'project-a', content: 'scope collision omega project evidence', createdAt: 2000 });
    const namedDuplicate = await kernel.ingest({ projectId: 'project-a', content: 'scope exact duplicate owner check', createdAt: 3000 });
    const globalDuplicate = await kernel.ingest({ content: 'scope exact duplicate owner check', createdAt: 4000 });
    kernel.recordRawEvent({ threadId: 'global-thread', role: 'user', content: 'scope collision omega global ledger' });
    kernel.recordRawEvent({ threadId: 'project-thread', projectId: 'project-a', role: 'user', content: 'scope collision omega project ledger' });
    kernel.activationStore.touch({ neuronId: globalNeuron.id, source: 'global-scope-test' });
    kernel.activationStore.touch({ neuronId: projectNeuron.id, projectId: 'project-a', source: 'global-scope-test' });

    expect(kernel.memoryGraph.fullTextSearch('scope collision omega', '', 20)).toContain(globalNeuron.id);
    expect(kernel.memoryGraph.fullTextSearch('scope collision omega', '', 20)).not.toContain(projectNeuron.id);
    expect(kernel.topologyStore.collectCandidateNeuronIds({ projectId: '', terms: ['scope collision omega'], limit: 50 })).toContain(globalNeuron.id);
    expect(kernel.topologyStore.collectCandidateNeuronIds({ projectId: '', terms: ['scope collision omega'], limit: 50 })).not.toContain(projectNeuron.id);
    const cognitive = kernel.cognitiveGraphStore.collectContext({ projectId: '', terms: ['scope collision omega'], limit: 50 });
    expect(cognitive.neuronIds).toContain(globalNeuron.id);
    expect(cognitive.neuronIds).not.toContain(projectNeuron.id);
    expect(kernel.eventStore.queryEvents(1, 100, { projectId: [''] }).records.every((event) => event.projectId === undefined)).toBe(true);
    expect(kernel.eventStore.searchRawEvents('scope collision omega', { projectId: '', limit: 20 }).every((event) => event.projectId === undefined)).toBe(true);
    const recalled = kernel.navigateMemory('scope collision omega', { projectId: '', limit: 50 });
    expect(recalled.rawEvidence.map((item) => item.id)).toContain(globalNeuron.id);
    expect(recalled.rawEvidence.map((item) => item.id)).not.toContain(projectNeuron.id);
    expect(globalDuplicate.id).not.toBe(namedDuplicate.id);
    expect(globalDuplicate.prev_hash).toBe(globalNeuron.self_hash);
    expect(kernel.buildMemoryMap({ projectId: '' }).counters.activationHotspots).toBe(1);
    kernel.close();
  });

  test('global maintenance, candidate views, reviews, and Dream backlog stay projectless-only', () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const db = kernel.factStore.getDatabase();
    for (const [runId, projectId] of [['global-run', ''], ['named-run', 'named']] as const) {
      db.prepare(`INSERT INTO deep_write_runs(run_id,project_id,source_neuron_ids_json,mode,prompt_hash,output_hash,status,created_at,updated_at) VALUES(?,?, '[]','shadow','p','o','succeeded',1,1)`).run(runId, projectId);
      db.prepare(`INSERT INTO deep_write_candidates(candidate_id,run_id,candidate_type,status,confidence,content_json,evidence_json,created_at,updated_at) VALUES(?,?, 'belief','needs_confirmation',1,'{}','{}',1,1)`).run(`${runId}-candidate`, runId);
      db.prepare(`INSERT INTO deep_write_candidate_reviews(review_id,candidate_id,project_id,action,actor,reason,from_status,to_status,decision_json,created_at) VALUES(?,?,?,'defer','test','reason','needs_confirmation','needs_confirmation','{}',1)`).run(`${runId}-review`, `${runId}-candidate`, projectId);
    }
    const globalRaw = kernel.recordRawEvent({ projectId: '', threadId: 'g', role: 'user', content: 'global', occurredAt: 1 });
    const namedRaw = kernel.recordRawEvent({ projectId: 'named', threadId: 'n', role: 'user', content: 'named', occurredAt: 2 });

    expect(kernel.listDreamCandidates({ projectId: '' }).map((item) => item.candidateId)).toEqual(['global-run-candidate']);
    expect(kernel.listDreamCandidateReviews({ projectId: '' }).map((item) => item.reviewId)).toEqual(['global-run-review']);
    expect(kernel.getDreamBacklogStatus('').rawEventCount).toBe(1);
    kernel.runMaintenanceTick({ projectId: '', now: 1000, confirmationTtlMs: 1 });
    expect(db.prepare(`SELECT candidate_id,status FROM deep_write_candidates ORDER BY candidate_id`).all()).toEqual([
      { candidate_id: 'global-run-candidate', status: 'superseded' },
      { candidate_id: 'named-run-candidate', status: 'needs_confirmation' },
    ]);
    kernel.markDreamed('', globalRaw.globalSeq!, 1);
    kernel.markDreamed('__global__', namedRaw.globalSeq!, 2);
    expect(db.prepare(`SELECT project_key FROM dream_ledger_state ORDER BY project_key`).all()).toEqual([
      { project_key: 'scope:0:' }, { project_key: 'scope:10:__global__' },
    ]);
    kernel.close();
  });

  test('projectless scope and a literal global project have distinct task and cluster identities', () => {
    const db = new Database(':memory:');
    db.exec(`CREATE TABLE neurons(id TEXT PRIMARY KEY,project_id TEXT,is_deleted INTEGER NOT NULL DEFAULT 0); INSERT INTO neurons VALUES('global-neuron',NULL,0)`);
    const topology = new TopologyStore(db);
    const globalTask = topology.upsertTaskBranch({ taskId: 'task-projectless', taskKey: 'same-task', title: 'Same task', createdAt: 1 });
    const namedTask = topology.upsertTaskBranch({ taskId: 'task-named', projectId: 'global', taskKey: 'same-task', title: 'Same task', createdAt: 2 });
    const globalCluster = topology.upsertEventCluster({ clusterId: 'cluster-projectless', clusterKey: 'generic:same', clusterType: 'generic', title: 'Same cluster', createdAt: 1 });
    const namedCluster = topology.upsertEventCluster({ clusterId: 'cluster-named', projectId: 'global', clusterKey: 'generic:same', clusterType: 'generic', title: 'Same cluster', createdAt: 2 });
    topology.attachToTask(globalTask.taskId, { projectId: undefined, neuronId: 'global-neuron', createdAt: 1 });
    topology.attachToTask(globalTask.taskId, { projectId: undefined, neuronId: 'global-neuron', createdAt: 1 });

    expect(globalTask.taskId).not.toBe(namedTask.taskId);
    expect(globalCluster.clusterId).not.toBe(namedCluster.clusterId);
    expect(() => topology.upsertTaskBranch({ taskId: globalTask.taskId, projectId: 'other', taskKey: 'other-task', title: 'Other task', createdAt: 3 })).toThrow();
    expect(() => topology.upsertEventCluster({ clusterId: globalCluster.clusterId, projectId: 'other', clusterKey: 'generic:other', clusterType: 'generic', title: 'Other cluster', createdAt: 3 })).toThrow();
    expect(topology.listTaskBranches('')).toHaveLength(1);
    expect(topology.listTaskBranches('global')).toHaveLength(1);
    expect(db.prepare(`SELECT COUNT(*) AS count FROM task_branch_entries WHERE task_id=?`).get(globalTask.taskId)).toEqual({ count: 1 });
    topology.close();
    db.close();
  });

  test('topology attach rejects every cross-project reference before writing', () => {
    const db = new Database(':memory:');
    db.exec(`
      CREATE TABLE neurons(id TEXT PRIMARY KEY,project_id TEXT,is_deleted INTEGER NOT NULL DEFAULT 0);
      CREATE TABLE facts(fact_id TEXT PRIMARY KEY,neuron_id TEXT);
      CREATE TABLE compiled_events(event_id TEXT PRIMARY KEY,neuron_id TEXT);
      CREATE TABLE beliefs(id TEXT PRIMARY KEY,project_id TEXT,source_neuron_id TEXT);
      CREATE TABLE belief_evidence(belief_id TEXT,neuron_id TEXT,event_id TEXT);
      CREATE TABLE interaction_units(unit_id TEXT PRIMARY KEY,message_neuron_ids_json TEXT);
      CREATE TABLE memory_events(event_id TEXT PRIMARY KEY,project_id TEXT);
      INSERT INTO neurons VALUES('a','a',0),('b','b',0);
      INSERT INTO facts VALUES('fact-b','b');
      INSERT INTO compiled_events VALUES('event-b','b');
      INSERT INTO beliefs VALUES('belief-b','b','b');
      INSERT INTO interaction_units VALUES('unit-b','["b"]');
    `);
    const topology = new TopologyStore(db);
    const task = topology.upsertTaskBranch({ taskId: 'task-a', projectId: 'a', taskKey: 'task', title: 'A', createdAt: 1 });
    for (const ref of [
      { neuronId: 'b' }, { factId: 'fact-b' }, { eventId: 'event-b' }, { beliefId: 'belief-b' }, { unitId: 'unit-b' },
    ]) {
      expect(() => topology.attachToTask(task.taskId, { projectId: 'a', ...ref, createdAt: 1 })).toThrow('topology_reference_project_scope_mismatch');
    }
    expect(db.prepare(`SELECT COUNT(*) AS count FROM task_branch_entries`).get()).toEqual({ count: 0 });
    topology.close(); db.close();
  });

  test('a stale writer cannot mark a newer source revision clean', () => {
    const dir = mkdtempSync(join(tmpdir(), 'cogmem-projection-cas-'));
    const dbPath = join(dir, 'memory.db');
    const writerA = new TopologyStore(dbPath);
    const writerB = new TopologyStore(dbPath);
    writerA.markTimeProjection('p', 'clean', 'UTC', 0, undefined, 0);

    const a = writerA.beginTimeProjectionSourceUpdate('p', 'UTC', 1);
    const b = writerB.beginTimeProjectionSourceUpdate('p', 'UTC', 2);
    expect(a).toEqual({ sourceRevision: 1, incremental: true });
    expect(b).toEqual({ sourceRevision: 2, incremental: false });
    expect(writerA.markTimeProjectionCleanIfCurrent('p', 'UTC', 3, a.sourceRevision)).toBe(false);
    expect(writerA.hasUsableTimeProjection('p', 'UTC')).toBe(false);
    expect(writerB.markTimeProjectionCleanIfCurrent('p', 'UTC', 4, b.sourceRevision)).toBe(true);
    expect(writerB.hasUsableTimeProjection('p', 'UTC')).toBe(true);
    writerA.close();
    writerB.close();
    rmSync(dir, { recursive: true, force: true });
  });

  test('two Kernel connections with different timezones cannot restore a partial projection to clean', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'cogmem-timezone-writers-'));
    const dbPath = join(dir, 'memory.db');
    const utc = createMemoryKernel({ dbPath, projectTimeZone: 'UTC' });
    await utc.ingest({ projectId: 'p', content: 'utc baseline', createdAt: 1000 });
    const tokyo = createMemoryKernel({ dbPath, projectTimeZone: 'Asia/Tokyo' });
    const foreignZone = await tokyo.ingest({ projectId: 'p', content: 'tokyo delta', createdAt: 2000 });
    const utcDelta = await utc.ingest({ projectId: 'p', content: 'utc delta after timezone conflict', createdAt: 3000 });
    const db = utc.factStore.getDatabase();
    expect(utc.topologyStore.hasUsableTimeProjection('p', 'UTC')).toBe(false);
    expect(db.prepare(`SELECT status,source_revision FROM topology_projection_state WHERE project_id='p'`).get()).toEqual({ status: 'dirty', source_revision: 3 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM time_bucket_entries WHERE neuron_id IN (?,?)`).get(foreignZone.id, utcDelta.id)).toEqual({ count: 0 });
    tokyo.close(); utc.close(); rmSync(dir, { recursive: true, force: true });
  });

  test('maintenance returns shell-safe structured rebuild arguments for untrusted project ids', async () => {
    const projectId = 'p; touch /tmp/cogmem-injected';
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    await kernel.ingest({ projectId, content: 'maintenance command safety evidence', createdAt: 1000 });
    kernel.topologyStore.markTimeProjection(projectId, 'dirty', 'UTC', 2);
    const action = kernel.runMaintenanceTick({ projectId }).suggestedActions.find((item) => item.kind === 'rebuild_topology');
    expect(action?.executable).toBe('cogmem');
    expect(action?.args).toEqual(['memory', 'rebuild-topology', '--project', projectId, '--json']);
    expect(action?.command).toContain("'p; touch /tmp/cogmem-injected'");
    kernel.close();
  });

  test('projection failure rolls back the neuron and a retry completes every derived surface', async () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const internals = kernel as unknown as { cognitiveGraphCompiler: { compile: (...args: unknown[]) => unknown } };
    const originalCompile = internals.cognitiveGraphCompiler.compile.bind(internals.cognitiveGraphCompiler);
    internals.cognitiveGraphCompiler.compile = () => { throw new Error('projection_fault_injection'); };

    await expect(kernel.ingest({ projectId: 'p', content: 'atomic projection retry evidence', createdAt: 1000 })).rejects.toThrow('projection_fault_injection');
    const db = kernel.factStore.getDatabase();
    expect(db.prepare(`SELECT COUNT(*) AS count FROM neurons WHERE project_id='p'`).get()).toEqual({ count: 0 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM memory_events WHERE project_id='p'`).get()).toEqual({ count: 0 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM topology_membership WHERE project_id='p'`).get()).toEqual({ count: 0 });

    internals.cognitiveGraphCompiler.compile = originalCompile;
    const neuron = await kernel.ingest({ projectId: 'p', content: 'atomic projection retry evidence', createdAt: 1000 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM neurons WHERE id=?`).get(neuron.id)).toEqual({ count: 1 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM topology_membership WHERE neuron_id=?`).get(neuron.id)).not.toEqual({ count: 0 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM cognitive_nodes WHERE source_neuron_id=?`).get(neuron.id)).not.toEqual({ count: 0 });
    kernel.close();
  });

  test('an empty project rebuild establishes a usable revision-zero projection', () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const rebuilt = kernel.rebuildProjectTimeTopology('empty-project');
    const db = kernel.factStore.getDatabase();

    expect(rebuilt.neurons).toBe(0);
    expect(db.prepare(`SELECT revision FROM topology_source_revisions WHERE project_id='empty-project'`).get()).toEqual({ revision: 0 });
    expect(db.prepare(`SELECT status,source_revision FROM topology_projection_state WHERE project_id='empty-project'`).get()).toEqual({ status: 'clean', source_revision: 0 });
    expect(kernel.topologyStore.hasUsableTimeProjection('empty-project', 'UTC')).toBe(true);
    kernel.close();
  });

  test('the first write after an empty rebuild remains an incremental clean projection', async () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    kernel.rebuildProjectTimeTopology('empty-project');

    await kernel.ingest({ projectId: 'empty-project', content: 'first temporal event', createdAt: 1000 });
    const db = kernel.factStore.getDatabase();
    expect(db.prepare(`SELECT revision FROM topology_source_revisions WHERE project_id='empty-project'`).get()).toEqual({ revision: 1 });
    expect(kernel.topologyStore.hasUsableTimeProjection('empty-project', 'UTC')).toBe(true);
    expect(db.prepare(`SELECT COUNT(*) AS count FROM time_bucket_entries WHERE project_id='empty-project'`).get()).toEqual({ count: 3 });
    kernel.close();
  });

  test('0051 repairs an upgraded projectless scope that has no projection state', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'cogmem-global-upgrade-'));
    const kernel = createMemoryKernel({ dbPath: join(dir, 'memory.db'), projectTimeZone: 'UTC' });
    await kernel.ingest({ content: 'legacy global scope', createdAt: Date.UTC(2026, 6, 17, 12) });
    const db = kernel.factStore.getDatabase();
    db.exec(`
      DELETE FROM _schema_migrations WHERE version='0051';
      UPDATE _meta SET value='50' WHERE key='schema_version';
      DELETE FROM topology_projection_state WHERE project_id='';
      DELETE FROM topology_source_revisions WHERE project_id='';
      DELETE FROM temporal_adjacency WHERE project_id='';
      DELETE FROM cognitive_edges WHERE project_id='' AND edge_type='occurred_in_time_bucket';
      DELETE FROM cognitive_nodes WHERE project_id='' AND node_type='time_bucket';
    `);

    const applied = new SchemaMigrationRunner(db, [migration_0051]).run();
    expect(applied.applied).toEqual(['0051']);
    expect(db.prepare(`SELECT status,source_revision FROM topology_projection_state WHERE project_id=''`).get()).toEqual({ status: 'dirty', source_revision: 0 });
    expect(db.prepare(`SELECT revision FROM topology_source_revisions WHERE project_id=''`).get()).toEqual({ revision: 1 });
    kernel.rebuildProjectTimeTopology();
    expect(kernel.topologyStore.hasUsableTimeProjection('', 'UTC')).toBe(true);
    kernel.close();
  });

  test('0051 gives an upgraded empty projection an explicit revision-zero watermark', () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const db = kernel.factStore.getDatabase();
    db.exec(`
      DELETE FROM _schema_migrations WHERE version='0051';
      UPDATE _meta SET value='50' WHERE key='schema_version';
      DELETE FROM topology_source_revisions WHERE project_id='empty-upgrade';
      INSERT INTO topology_projection_state(project_id,projection_version,status,time_zone,updated_at,error,source_revision)
      VALUES('empty-upgrade',3,'clean','UTC',1,NULL,0)
      ON CONFLICT(project_id) DO UPDATE SET projection_version=3,status='clean',time_zone='UTC',source_revision=0;
    `);

    const applied = new SchemaMigrationRunner(db, [migration_0051]).run();
    expect(applied.applied).toEqual(['0051']);
    expect(db.prepare(`SELECT revision FROM topology_source_revisions WHERE project_id='empty-upgrade'`).get()).toEqual({ revision: 0 });
    expect(kernel.topologyStore.hasUsableTimeProjection('empty-upgrade', 'UTC')).toBe(false);
    kernel.rebuildProjectTimeTopology('empty-upgrade');
    expect(kernel.topologyStore.hasUsableTimeProjection('empty-upgrade', 'UTC')).toBe(true);
    kernel.close();
  });

  test('dirty projection ingest never writes partial main temporal state', async () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    await kernel.ingest({ projectId: 'p', content: 'first clean temporal event', createdAt: 1000 });
    const db = kernel.factStore.getDatabase();
    kernel.topologyStore.markTimeProjection('p', 'dirty', 'UTC', 2);
    const beforeEntries = db.prepare(`SELECT COUNT(*) AS count FROM time_bucket_entries WHERE project_id='p'`).get();
    const beforeNodes = db.prepare(`SELECT COUNT(*) AS count FROM cognitive_nodes WHERE project_id='p' AND node_type='time_bucket'`).get();

    await kernel.ingest({ projectId: 'p', content: 'second event while projection is dirty', createdAt: 2000 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM time_bucket_entries WHERE project_id='p'`).get()).toEqual(beforeEntries);
    expect(db.prepare(`SELECT COUNT(*) AS count FROM cognitive_nodes WHERE project_id='p' AND node_type='time_bucket'`).get()).toEqual(beforeNodes);
    const navigation = kernel.navigateMemory('today', { projectId: 'p', now: 2000, localDateNow: '1970-01-01', timeZone: 'UTC' });
    expect(navigation.navigation?.branchSearch.temporalTraversal.neuronIds).toEqual([]);
    expect(navigation.navigation?.branchSearch.temporalTraversal.traversalMode).toBe('disabled');
    expect(navigation.navigation?.pulse.temporalNeuronIds ?? []).toEqual([]);
    kernel.close();
  });

  test('stale ready rebuild is replaced when source revision changes', async () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    await kernel.ingest({ projectId: 'p', content: 'source revision one', createdAt: 1000 });
    const db = kernel.factStore.getDatabase();
    const staleRevision = kernel.topologyStore.getTimeProjectionSourceRevision('p');
    db.prepare(`INSERT INTO topology_time_rebuild_jobs(project_id,generation,time_zone,status,neuron_count,updated_at,source_revision) VALUES('p','stale-ready','UTC','ready',1,1,?)`).run(staleRevision);
    kernel.topologyStore.markTimeProjection('p', 'building', 'UTC', 1, undefined, staleRevision);
    await kernel.ingest({ projectId: 'p', content: 'source revision two', createdAt: 2000 });

    const rebuilt = kernel.rebuildProjectTimeTopology('p');
    expect(rebuilt.neurons).toBe(2);
    expect(kernel.topologyStore.hasUsableTimeProjection('p', 'UTC')).toBe(true);
    expect(db.prepare(`SELECT COUNT(DISTINCT neuron_id) AS count FROM time_bucket_entries WHERE project_id='p'`).get()).toEqual({ count: 2 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM topology_time_rebuild_jobs WHERE project_id='p'`).get()).toEqual({ count: 0 });
    kernel.close();
  });

  test('a rebuild must own the ready job before replacing the live projection', async () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const neuron = await kernel.ingest({ projectId: 'p', content: 'projection that must survive a lost publish claim', createdAt: 1000 });
    const db = kernel.factStore.getDatabase();
    const liveEntries = db.prepare(`SELECT COUNT(*) AS count FROM time_bucket_entries WHERE project_id='p'`).get();
    const sourceRevision = kernel.topologyStore.getTimeProjectionSourceRevision('p');
    db.exec(`
      INSERT INTO topology_time_rebuild_jobs(project_id,generation,time_zone,status,neuron_count,updated_at,source_revision)
      VALUES('p','claim-race','UTC','ready',1,1,${sourceRevision});
      CREATE TRIGGER simulate_lost_rebuild_claim
      BEFORE UPDATE OF updated_at ON topology_time_rebuild_jobs
      WHEN OLD.project_id='p' AND OLD.generation='claim-race' AND OLD.status='ready'
      BEGIN
        DELETE FROM topology_time_rebuild_jobs WHERE project_id=OLD.project_id AND generation=OLD.generation;
      END;
    `);

    expect(() => kernel.rebuildProjectTimeTopology('p')).toThrow('time_projection_rebuild_publish_conflict');
    expect(db.prepare(`SELECT COUNT(*) AS count FROM time_bucket_entries WHERE project_id='p'`).get()).toEqual(liveEntries);
    expect(kernel.topologyStore.hasUsableTimeProjection('p', 'UTC')).toBe(false);
    expect(kernel.topologyStore.listTimeBucketIdsByNeuronIds([neuron.id], 'p')).toEqual([]);
    db.exec(`DROP TRIGGER simulate_lost_rebuild_claim`);
    kernel.close();
  });

  test('a competing publisher returns busy without failing the active owner', () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const db = kernel.factStore.getDatabase();
    db.prepare(`INSERT INTO topology_time_rebuild_jobs(project_id,generation,time_zone,status,neuron_count,updated_at,source_revision,publish_token,publish_lease_until) VALUES('p','owned','UTC','ready',0,1,0,'owner',?)`).run(Date.now() + 60_000);
    kernel.topologyStore.markTimeProjection('p', 'building', 'UTC', 1, undefined, 0);

    expect(() => kernel.rebuildProjectTimeTopology('p')).toThrow('time_projection_rebuild_publish_conflict');
    expect(db.prepare(`SELECT status,publish_token FROM topology_time_rebuild_jobs WHERE project_id='p'`).get()).toEqual({ status: 'ready', publish_token: 'owner' });
    kernel.close();
  });

  test('projection publish crosses the 500-row boundary without one unbounded write transaction', () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const db = kernel.factStore.getDatabase();
    const generation = 'bounded-publish';
    db.prepare(`INSERT INTO topology_time_rebuild_jobs(project_id,generation,time_zone,status,neuron_count,updated_at,source_revision,publish_token,publish_lease_until) VALUES('bulk',?,'UTC','ready',501,1,0,'crashed-owner',NULL)`).run(generation);
    kernel.topologyStore.markTimeProjection('bulk', 'building', 'UTC', 1, undefined, 0);
    db.prepare(`INSERT INTO topology_time_rebuild_buckets(generation,bucket_id,project_id,time_zone,bucket_type,bucket_start,bucket_end,label) VALUES(?,'bulk-day','bulk','UTC','day',0,86400000,'day')`).run(generation);
    const active = db.prepare(`INSERT INTO topology_time_rebuild_active_neurons(generation,neuron_id,project_id,created_at,title) VALUES(?,?,'bulk',?,'title')`);
    const entry = db.prepare(`INSERT INTO topology_time_rebuild_entries(generation,bucket_id,neuron_id,project_id,created_at) VALUES(?,'bulk-day',?,'bulk',?)`);
    db.transaction(() => { for (let index = 0; index < 501; index += 1) { const id = `bulk-${index}`; active.run(generation, id, index); entry.run(generation, id, index); } })();
    expect(kernel.rebuildProjectTimeTopology('bulk')).toMatchObject({ neurons: 501, buckets: 1 });
    expect(db.prepare(`SELECT COUNT(*) AS count FROM time_bucket_entries WHERE project_id='bulk'`).get()).toEqual({ count: 501 });
    expect(kernel.topologyStore.hasUsableTimeProjection('bulk', 'UTC')).toBe(true);
    kernel.close();
  });

  test('direct neuron writers atomically dirty the source revision', async () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    await kernel.ingest({ projectId: 'p', content: 'initial clean projection', createdAt: 1000 });
    const before = kernel.topologyStore.getTimeProjectionSourceRevision('p');
    const direct = NeuronFactory.create(
      'direct semantic writer',
      kernel.memoryGraph.getLatestNeuronSelfHash('p') || 'genesis',
      { T: 2000, S: [0, 0, 0], V: [] },
      { projectId: 'p', type: 'semantic_consolidation', createdAt: 2000, updatedAt: 2000 },
    );

    kernel.memoryGraph.addNeuron(direct);
    expect(kernel.topologyStore.getTimeProjectionSourceRevision('p')).toBe(before + 1);
    expect(kernel.topologyStore.hasUsableTimeProjection('p', 'UTC')).toBe(false);
    kernel.rebuildProjectTimeTopology('p');
    expect(kernel.factStore.getDatabase().prepare(`SELECT COUNT(DISTINCT neuron_id) AS count FROM time_bucket_entries WHERE project_id='p'`).get()).toEqual({ count: 2 });

    expect(() => kernel.memoryGraph.updateNeuronMetadata(direct.id, { projectId: 'moved', updatedAt: 3000 })).toThrow('immutable_neuron_project_scope');
    expect(kernel.memoryGraph.getNeuronIdsByProject('p')).toContain(direct.id);
    expect(kernel.memoryGraph.getNeuronIdsByProject('moved')).not.toContain(direct.id);
    kernel.close();
  });

  test('Universe query compilation uses the caller project clock', () => {
    const kernel = createMemoryKernel({ projectTimeZone: 'UTC' });
    const now = Date.UTC(2026, 6, 16, 15, 30);
    const result = kernel.navigateMemory('today', { projectId: 'p', now, localDateNow: '2026-07-17', timeZone: 'Asia/Tokyo' });
    const expected = localDateRange(2026, 7, 17, 2026, 7, 18, 'Asia/Tokyo');
    expect(result.navigation?.compiledQuery.ir.temporal.start).toBe(expected.from);
    expect(result.navigation?.compiledQuery.ir.temporal.end).toBe(expected.to);
    kernel.close();
  });

  test('a clean projection becomes unavailable when the Kernel timezone changes', async () => {
    const dir = mkdtempSync(join(tmpdir(), 'cogmem-timezone-validity-'));
    const dbPath = join(dir, 'memory.db');
    let kernel = createMemoryKernel({ dbPath, projectTimeZone: 'UTC' });
    await kernel.ingest({ projectId: 'p', content: 'timezone-sensitive projection', createdAt: Date.UTC(2026, 6, 17, 0) });
    expect(kernel.topologyStore.hasUsableTimeProjection('p', 'UTC')).toBe(true);
    kernel.close();

    kernel = createMemoryKernel({ dbPath, projectTimeZone: 'Asia/Tokyo' });
    expect(kernel.topologyStore.hasUsableTimeProjection('p', 'Asia/Tokyo')).toBe(false);
    const result = kernel.navigateMemory('today', { projectId: 'p', now: Date.UTC(2026, 6, 17, 0), timeZone: 'Asia/Tokyo' });
    expect(result.navigation?.branchSearch.temporalTraversal.neuronIds).toEqual([]);
    kernel.close();
  });

  test('bucket identity includes timezone and DST-sensitive end boundaries', () => {
    const utc = localDateRange(2026, 3, 29, 2026, 3, 30, 'UTC');
    const london = localDateRange(2026, 3, 29, 2026, 3, 30, 'Europe/London');
    expect(utc.from).toBe(london.from);
    expect(utc.to).not.toBe(london.to);
    const utcId = timeBucketId({ projectId: 'p', timeZone: 'UTC', bucketType: 'day', bucketStart: utc.from, bucketEnd: utc.to });
    const londonId = timeBucketId({ projectId: 'p', timeZone: 'Europe/London', bucketType: 'day', bucketStart: london.from, bucketEnd: london.to });
    expect(utcId).not.toBe(londonId);
  });

  test('stores reject forged cross-project bucket and cognitive edge identities', () => {
    const db = new Database(':memory:');
    const topology = new TopologyStore(db);
    topology.upsertTimeBucket({ ...bucket('shared-id', 0, 10), projectId: 'a', timeZone: 'UTC' });
    expect(() => topology.upsertTimeBucket({ ...bucket('shared-id', 0, 10), projectId: 'b', timeZone: 'UTC' })).toThrow('time_bucket_identity_conflict');
    expect(() => topology.attachToTimeBucket('shared-id', { projectId: 'b', neuronId: 'n', createdAt: 0 })).toThrow('time_bucket_project_scope_mismatch');

    const graph = new CognitiveGraphStore(db);
    const a = graph.upsertNode({ nodeId: 'ignored-a', nodeType: 'entity', nodeKey: 'a', title: 'a', projectId: 'a', createdAt: 0 });
    const b = graph.upsertNode({ nodeId: 'ignored-b', nodeType: 'entity', nodeKey: 'b', title: 'b', projectId: 'b', createdAt: 0 });
    expect(() => graph.linkNodes({ sourceNodeId: a.nodeId, targetNodeId: b.nodeId, edgeType: 'mentions_entity', projectId: 'a', createdAt: 0 })).toThrow('cognitive_edge_project_scope_mismatch');
    expect(graph.collectContext({ projectId: 'a', seedNodeIds: [b.nodeId] }).seedNodeIds).toEqual([]);
    graph.close();
    topology.close();
  });

  test('global cognitive seeds still honor temporal exclusion', () => {
    const db = new Database(':memory:');
    const store = new CognitiveGraphStore(db);
    const time = store.upsertNode({ nodeId: 'time', nodeType: 'time_bucket', nodeKey: 'time:day', title: 'day', createdAt: 1 });
    const neuron = store.upsertNode({ nodeId: 'neuron', nodeType: 'neuron', nodeKey: 'neuron:n', title: 'memory', sourceNeuronId: 'n', createdAt: 1 });
    const context = store.collectContext({ seedNodeIds: [time.nodeId, neuron.nodeId], excludeTemporal: true });
    expect(context.seedNodeIds).toEqual([neuron.nodeId]);
    store.close();
  });
});
